import { build } from 'esbuild';
import { mkdir, rm, cp, copyFile, writeFile, readFile } from 'node:fs/promises';
await rm('dist', { recursive: true, force: true });
await mkdir('dist/client', { recursive: true });
await mkdir('dist/server', { recursive: true });
await mkdir('dist/.openai', { recursive: true });
await cp('public', 'dist/client', { recursive: true });
await copyFile('src/client/styles.css', 'dist/client/styles.css');
await build({ entryPoints: ['src/client/app.js'], bundle: true, format: 'esm', target: 'es2022', outfile: 'dist/client/app.js' });
await build({ entryPoints: ['src/server/index.js'], bundle: true, format: 'esm', platform: 'browser', target: 'es2022', outfile: 'dist/server/index.js' });
const manifest = JSON.parse(await readFile('.openai/hosting.json', 'utf8'));
await writeFile('dist/.openai/hosting.json', JSON.stringify(manifest, null, 2) + '\n');
console.log('Built browser app and provider-neutral Worker. No model configured.');
