import {recipes,topics,articles,constitutions,sources,lifestyle} from './data.js';
import {isExplicitUrgent,isSensitive} from '../shared/safety.js';
import {getAgentReply} from './agent-client.js';
import {openStorage} from './storage.js';
import {defaultProfile,emptyState} from '../shared/records.js';
import {createAssessmentUI} from './assessment-ui.js';
import {createDietPages,friendlyMessage} from './diet-page.js';
import {createId} from '../shared/id.js';
const icons={home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z"/><path d="M9 21v-8h6v8"/>',leaf:'<path d="M20 3c-9-1-16 3-16 10a7 7 0 0 0 7 7C18 20 21 12 20 3Z"/><path d="m4 21 11-12"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',spark:'<path d="m12 3 2.6 6.4L21 12l-6.4 2.6L12 21l-2.6-6.4L3 12l6.4-2.6Z"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',bookmark:'<path d="M6 3h12v18l-6-4-6 4z"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',moon:'<path d="M21 13A9 9 0 0 1 11 3 9 9 0 1 0 21 13Z"/>',wind:'<path d="M3 8h12a3 3 0 1 0-3-3M3 12h15a3 3 0 1 1-3 3M3 16h5"/>',scale:'<path d="M4 5h16v16H4z"/><path d="M8 9a5 5 0 0 1 8 0M12 8v3"/>',bowl:'<path d="M3 12h18c0 6-5 8-9 8s-9-2-9-8Z"/><path d="M7 5v3m5-5v5m5-3v3"/>',check:'<path d="m5 12 4 4L19 6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',back:'<path d="m14 5-7 7 7 7"/>',book:'<path d="M3 3h6a4 4 0 0 1 3 2 4 4 0 0 1 3-2h6v17h-6a4 4 0 0 0-3 2 4 4 0 0 0-3-2H3zM12 5v17"/>',cup:'<path d="M4 7h13v8a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5zM17 8h2a3 3 0 0 1 0 6h-2M7 3v1m4-1v1m4-1v1"/>',camera:'<path d="M4 8h3l2-3h6l2 3h3a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V10a2 2 0 0 1 2-2z"/><circle cx="12" cy="13" r="3.2"/>',send:'<path d="m22 2-7 20-4-9-9-4z"/><path d="M22 2 11 13"/>'};
const icon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.leaf}</svg>`;
const esc=(s)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dietPages=createDietPages({getState:()=>state,writeStore,toast,navigate,openDetail,icon,esc,render:()=>render()});
let state=emptyState(),page='home',foodTab='全部',careTab='全部',day='今日',homeMode='三餐',toastTimer,chatBusy=false,history=[],chatVersion=0;
let storage=null,storageError='',dataEpoch=0,clearing=false,writeQueue=Promise.resolve(),requestController=null,activePlan=null,contentRef=null,urgentSession=false;
async function refreshState(){const epoch=dataEpoch;const next=await storage.load();if(epoch===dataEpoch){state=next;render()}}
async function writeStore(action){if(!storage||clearing)throw new Error('本机存储暂不可用，请稍后重试');const epoch=dataEpoch;const task=writeQueue.catch(()=>{}).then(()=>{if(epoch!==dataEpoch)throw new Error('操作已取消');return action(storage)});writeQueue=task;const value=await task;if(epoch===dataEpoch)await refreshState();return value}
async function bootStorage(){try{storage=await openStorage();storageError=''}catch{storageError='本浏览器暂时无法读取或保存本机记录。你仍可浏览内容；请重试存储或检查浏览器设置。'}await dietPages.loadCatalog();if(storage)await refreshState();else render()}

let pendingPlans=new Map();
const main=document.getElementById('main'),detail=document.getElementById('detail-dialog'),chat=document.getElementById('chat-dialog');
const assessment=createAssessmentUI({show:openDetail,storage:()=>{if(!storage||clearing)throw new Error('本机存储不可用，暂时无法保存');return storage},changed:refreshState,notify:toast});
function toast(s){clearTimeout(toastTimer);const el=document.getElementById('toast');el.textContent=s;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),2500)}
function paintIcons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon))}
function heading(title,sub,english='YOUR WELLNESS SPACE'){const now=new Date();return`<div class="page-heading"><div><p class="eyebrow">${english}</p><h1>${title}</h1><p>${sub}</p></div><div class="date-stamp"><strong>${String(now.getMonth()+1).padStart(2,'0')}<span>/${String(now.getDate()).padStart(2,'0')}</span></strong><span>今天 · 好好生活</span></div></div>`}
function sectionHead(title,label,button=''){return`<div class="section-heading"><div><span class="eyebrow">${label}</span><h2>${title}</h2></div>${button}</div>`}
function recipeCard(r,compact=false){return`<button class="recipe-tile ${compact?'compact':''}" data-recipe="${r.id}">${r.image?`<img src="${r.image}" alt="${r.title}食物示意" loading="lazy">`:`<div class="recipe-type-art ${r.id==='breakfast'?'amber':''}">${icon(r.id==='tea'?'cup':'bowl')}<span>${r.time}</span></div>`}<div class="recipe-tile-body"><span class="tag">${r.tag}</span><h3>${r.title}</h3><p>${r.desc}</p><div class="recipe-meta"><span>${r.duration}</span><span>查看搭配 ${icon('arrow')}</span></div></div></button>`}
function topicCard(t){return`<button class="topic-card" data-topic="${t.id}"><span class="topic-symbol ${t.accent}">${icon(t.icon)}</span><span><strong>${t.title}</strong><small>${t.subtitle}</small></span>${icon('arrow')}</button>`}
function articleCard(a){return`<button class="article-card" data-article="${a.id}"><img src="${a.image}" alt="${a.label}配图" loading="lazy"><div><span class="article-label">${a.label}</span><h3>${a.title}</h3><span class="small muted">${a.read}阅读 · 内容示例</span></div></button>`}
function profileMini(){return`<section class="profile-card"><div class="section-mini"><span>我的健康档案</span>${icon('user')}</div><span class="subtle-label">从认识自己开始</span><h2>${state.assessments.length?'已记录 '+state.assessments.length+' 次感受':'每个人，都有自己的节奏。'}</h2><p>当前目标：${esc(state.profile.goal)}<br>档案与记录，仅保存在本机。</p><div class="profile-tags"><span>${esc(state.profile.preference)}</span><span>体质测评 · 试测中</span></div><button class="outline-button" data-page="profile">查看我的档案 ${icon('arrow')}</button></section>`}
function home(){return dietPages.record()}
function today(){return dietPages.today()}
function library(){return dietPages.library()}
function food(){const options=['全部','三餐搭配','食养茶饮','起居建议','文章'];const visible=recipes.filter(r=>foodTab==='全部'||r.category===foodTab);return`${heading('一日三餐，一点食养。','把适合自己的搭配，慢慢放进生活。','FOOD & EVERYDAY LIVING')}<div class="food-banner"><img src="assets/lunch.jpg" alt="中式三餐搭配示意"><div><span class="subtle-label">从家常饭开始</span><h2>好好吃饭，是每天的小事。</h2><p>食谱、茶饮和起居参考，<br>也可以交给知养一起帮你选。</p><button class="primary-button" data-chat="帮我安排一日三餐">${icon('spark')} 帮我安排三餐</button></div></div><div class="filter-row" aria-label="食养分类">${options.map(x=>`<button data-food-tab="${x}" class="filter-chip ${foodTab===x?'active':''}" aria-pressed="${foodTab===x}">${x}</button>`).join('')}</div>${foodTab==='三餐搭配'?`<div class="inline-heading"><h2>${day}三餐参考</h2><div class="segmented"><button data-day="今日" class="${day==='今日'?'active':''}">今日</button><button data-day="明日" class="${day==='明日'?'active':''}">明日</button></div></div><p class="muted section-note">示例安排，可按你的偏好替换；份量未做个人计算。</p>`:''}${foodTab==='文章'?`<div class="article-grid">${articles.map(articleCard).join('')}</div>`:foodTab==='起居建议'?`<div class="routine-card"><span class="routine-icon">${icon('moon')}</span><div><span class="tag">晚间起居</span><h3>${lifestyle.title}</h3><p>${lifestyle.desc}</p></div><button class="primary-button" data-lifestyle="sleep">查看建议</button></div>`:`<div class="food-grid">${(foodTab==='三餐搭配'&&day==='明日'?[recipes[0],{...recipes[2],time:'午餐'},{...recipes[1],time:'晚餐'}]:visible).map(r=>recipeCard(r)).join('')}</div>`}<div class="small-notice">${icon('book')} 本页为内容与交互示例。可在详情中查看参考来源和适用说明。</div>`}
function care(){const groups=['全部','日常状态','呼吸与咽喉','脾胃与消化','作息与情绪'];return`${heading('身体的小信号，认真听。','从你的感受出发，看看日常生活可以怎样调整。','CARE & DAILY WELLBEING')}<div class="care-intro"><span class="care-intro-icon">${icon('heart')}</span><div><h2>日常调养，也要有分寸。</h2><p>以下为一般生活、饮食与休息参考，不用于诊断或治疗。<br>涉及医疗用途，请咨询医生；持续或明显不适时，优先寻求专业帮助。</p></div><button class="outline-button" data-chat="我想聊聊最近的身体感受">${icon('spark')} 和助手聊聊</button></div><section class="section">${sectionHead('当下热门','COMMON CONCERNS')}<div class="filter-row">${groups.map(x=>`<button class="filter-chip ${careTab===x?'active':''}" data-care-tab="${x}" aria-pressed="${careTab===x}">${x}</button>`).join('')}</div><div class="care-grid">${topics.filter(t=>careTab==='全部'||t.group===careTab).map(t=>`<button class="care-tile" data-topic="${t.id}"><span class="topic-symbol ${t.accent}">${icon(t.icon)}</span><span class="small muted">${t.group}</span><h3>${t.title}</h3><p>${t.subtitle}</p><span class="meal-link">生活建议 · 食养参考 ${icon('arrow')}</span></button>`).join('')}</div></section><div class="feature-line"><div><span class="eyebrow">KNOW YOURSELF</span><h3>湿气重，就是痰湿质吗？</h3><p>日常感受与正式体质判定有区别。先了解九种基本类型。</p></div><button class="outline-button" data-action="constitutions">了解九种体质 ${icon('arrow')}</button></div>`}
function planCard(p){return`<article class="saved-plan"><div class="section-mini"><span>${esc(p.goal)} · 示例 · 修订 ${p.revision}</span><button class="icon-button" data-remove-plan="${esc(p.id)}" aria-label="移除${esc(p.title)}">${icon('close')}</button></div><h3>${esc(p.title)}</h3><dl>${p.meals.map(m=>`<div><dt>${esc(m.label)}</dt><dd>${esc(m.value)}</dd></div>`).join('')}</dl><p class="small muted">${esc(p.note)}</p><button class="text-button" data-adjust-plan="${esc(p.id)}">和助手一起调整 ${icon('arrow')}</button></article>`}
function legacyProfile(){const p=state.profile;return`${heading('更了解你，才能更贴近你。','你的档案、收藏和方案，放在一起。','MY WELLNESS SPACE')}<section class="profile-overview"><span class="big-avatar">${esc((p.name||'养').slice(0,1))}</span><div><span class="subtle-label">个人档案 · 仅在本机</span><h2>${esc(p.name)}</h2><p>${esc(p.goal)} · ${esc(p.habit)}</p></div><button class="outline-button" data-action="edit-profile">编辑档案</button></section><div class="profile-sections"><section class="constitution-panel"><div class="section-mini"><span>体质与日常感受</span><span class="tag">新问卷 · 试测阶段</span></div><h2>认识自己，慢慢来。</h2><p>32 道候选题，记录过去一年的日常感受。支持本机草稿和多次记录；当前不作正式体质判定。</p><div class="button-row"><button class="primary-button" data-action="quiz">${state.draft?'继续或开始试测':'开始日常感受试测'} ${icon('arrow')}</button><button class="text-button" data-action="constitutions">九种体质科普</button></div><span class="small muted">题目与判定规则仍需专业审核和验证。</span></section><section class="preferences-panel"><span class="subtle-label">我希望，养成这样的生活</span><h3>${esc(p.goal)}</h3><div class="preference-row"><span>用餐习惯</span><strong>${esc(p.habit)}</strong></div><div class="preference-row"><span>饮食偏好</span><strong>${esc(p.preference)}</strong></div><button class="text-button" data-action="edit-profile">调整我的偏好 ${icon('arrow')}</button></section></div><section class="section">${assessmentHistory()}${sectionHead('我的方案','MY PLANS',`<span class="count-label">${state.plans.length} 份</span>`)}${state.plans.length?`<div class="plans-grid">${state.plans.map(planCard).join('')}</div>`:`<div class="empty-state">${icon('spark')}<div><h3>从一次咨询开始</h3><p>让助手给出方案，点击保存，就能在这里继续查看。</p></div><button class="outline-button" data-chat="我想健康减重">体验一次咨询</button></div>`}</section><section class="section">${sectionHead('我的收藏','SAVED FOR LATER',`<span class="count-label">${state.saved.length} 项</span>`)}${state.saved.length?`<div class="saved-grid">${state.saved.map(key=>{const [type,id]=key.split(':');const item=(type==='recipe'?recipes:articles).find(x=>x.id===id);return item?`<button class="saved-item" data-${type}="${id}">${icon(type==='recipe'?'bowl':'book')}<span>${esc(item.title)}</span>${icon('arrow')}</button>`:''}).join('')}</div>`:`<p class="empty-copy">喜欢的食谱、茶饮和文章，可以先收藏，慢慢看。</p>`}</section><div class="privacy-line"><p>档案、收藏、方案和测评只存在当前浏览器，换设备不会同步。发送咨询会把本次问题与当前对话发给服务端；勾选后才附带饮食偏好。请使用虚构信息体验。</p><button class="text-button" data-action="reset">清除本地演示数据</button></div>`}
function profile(){return dietPages.settings()}
function render(){document.querySelectorAll('[data-page]').forEach(b=>{b.classList.toggle('active',b.dataset.page===page&&b.classList.contains('nav-item'));if(b.classList.contains('nav-item'))b.setAttribute('aria-current',b.dataset.page===page?'page':'false')});main.innerHTML=(storageError?`<div class="storage-error" role="alert">${esc(storageError)} <button class="text-button" data-action="retry-storage">重试存储</button></div>`:'')+({home,today,library,food,care,profile}[page]||home)();document.querySelector('.topbar-label').textContent='知养';paintIcons();}
function navigate(next,replace=false){if(!['home','today','library','profile'].includes(next))return;page=next;render();historyAPI(replace);window.scrollTo({top:0,behavior:'instant'});}
function historyAPI(replace){window.history[replace?'replaceState':'pushState']({},'',`#${page}`)}
window.addEventListener('popstate',()=>{page=location.hash.slice(1)||'home';if(!['home','today','library','profile'].includes(page))page='home';render()});
function detailHeader(label){return`<div class="dialog-toolbar"><span>${label}</span><button class="icon-button" data-close="detail" aria-label="关闭详情">${icon('close')}</button></div>`}
function openDetail(html,label='内容详情'){document.getElementById('detail-content').innerHTML=detailHeader(label)+html;detail.setAttribute('aria-label',label);if(!detail.open)detail.showModal();detail.scrollTop=0;}
const sourceHtml=(key)=>sources[key]?`<details class="source-details"><summary>参考来源与内容说明</summary><p>页面文案为 Demo 编排示例，未经过完整专业审核。下列来源提供相关一般原则，不是对本方案的验证。</p><a href="${sources[key].url}" target="_blank" rel="noopener noreferrer">${sources[key].title} ↗</a></details>`:'';
function recipeDetail(id){const r=recipes.find(x=>x.id===id);if(!r)return;const saved=state.saved.includes('recipe:'+id);openDetail(`${r.image?`<img class="detail-cover" src="${r.image}" alt="${r.title}示意图">`:''}<div class="detail-body"><span class="tag">${r.category} · 示例</span><h2>${r.title}</h2><p class="detail-lead">${r.desc}</p><div class="detail-meta">${icon('clock')} ${r.duration}<span>·</span>日常食养参考</div><h3>准备这些食材</h3><div class="ingredient-list">${r.ingredients.map(x=>`<span>${x}</span>`).join('')}</div><h3>可以这样搭配</h3><ol class="step-list">${r.steps.map(x=>`<li>${x}</li>`).join('')}</ol><div class="gentle-note">${r.note}</div>${sourceHtml(r.source)}<div class="detail-actions"><button class="primary-button" data-ref-type="recipe" data-ref-id="${r.id}" data-detail-chat="${r.id==='tea'?'推荐一杯养生茶':`这道${r.title}怎么加入我的三餐？`}">${icon('spark')} 结合我的情况问问 AI</button><button class="outline-button" data-save="recipe:${r.id}">${icon('bookmark')} ${saved?'已收藏':'收藏'}</button></div></div>`,'食养详情')}
function topicDetail(id){const t=topics.find(x=>x.id===id);if(!t)return;openDetail(`<div class="detail-body"><span class="topic-symbol ${t.accent}">${icon(t.icon)}</span><span class="tag">${t.group} · 专题示例</span><h2>${t.title}</h2><p class="detail-lead">${t.subtitle}</p><div class="boundary-note"><strong>先看适用边界</strong><p>${t.boundary}</p></div><h3>日常生活可以先留意</h3><ol class="step-list">${t.tips.map(x=>`<li>${x}</li>`).join('')}</ol>${t.related?`<h3>相关食养灵感</h3><p class="small muted">仅为内容关联示例，不代表对这一症状有效。</p><button class="related-card" data-recipe="${t.related}">${icon('bowl')}<span>${recipes.find(r=>r.id===t.related).title}</span>${icon('arrow')}</button>`:''}${sourceHtml(t.source)}<div class="detail-actions"><button class="primary-button" data-ref-type="topic" data-ref-id="${t.id}" data-detail-chat="${t.title}">${icon('spark')} 把我的情况告诉 AI</button></div></div>`,'日常调养')}
function articleDetail(id){const a=articles.find(x=>x.id===id);if(!a)return;openDetail(`<img class="detail-cover" src="${a.image}" alt="${a.label}配图"><article class="detail-body article-body"><span class="tag">${a.label}</span><h2>${a.title}</h2><p class="small muted">知养内容示例 · ${a.read}阅读</p><p class="detail-lead">${a.intro}</p>${a.paragraphs.map(([h,p])=>`<h3>${h}</h3><p>${p}</p>`).join('')}${sourceHtml(a.source)}<div class="detail-actions"><button class="primary-button" data-ref-type="article" data-ref-id="${a.id}" data-detail-chat="如何把${a.label}用到我的一日三餐？">${icon('spark')} 和助手聊聊这篇文章</button><button class="outline-button" data-save="article:${a.id}">${icon('bookmark')} ${state.saved.includes('article:'+id)?'已收藏':'收藏'}</button></div></article>`,'食养文章')}
function lifestyleDetail(){openDetail(`<div class="detail-body"><span class="topic-symbol purple">${icon('moon')}</span><span class="tag">起居建议</span><h2>${lifestyle.title}</h2><p class="detail-lead">${lifestyle.desc}</p><ol class="step-list">${lifestyle.points.map(p=>`<li>${p}</li>`).join('')}</ol><div class="gentle-note">安排要符合你的真实作息。持续睡眠困扰应寻求专业帮助。</div><button class="primary-button" data-detail-chat="帮我调整作息">${icon('spark')} 帮我安排今晚</button></div>`,'晚间起居')}
function editProfile(){const p=state.profile;openDetail(`<div class="detail-body"><span class="tag">仅在本浏览器保存</span><h2>让建议，更贴近你的生活</h2><p class="detail-lead">这里可以使用虚构信息体验，不必填写真实健康资料。</p><form id="profile-form"><label class="form-label">怎么称呼你<input name="name" maxlength="20" value="${esc(p.name)}" required autocomplete="off"></label><label class="form-label">当前最想关注的目标<select name="goal">${['均衡饮食','健康减重','健康增重','规律作息'].map(v=>`<option ${v===p.goal?'selected':''}>${v}</option>`).join('')}</select></label><label class="form-label">平时怎样吃饭<select name="habit">${['自己做饭与外食都有','主要自己做饭','主要在外吃饭'].map(v=>`<option ${v===p.habit?'selected':''}>${v}</option>`).join('')}</select></label><label class="form-label">饮食偏好<select name="preference">${['暂无偏好','偏爱家常中餐','更喜欢清淡口味','不喜欢吃鱼'].map(v=>`<option ${v===p.preference?'selected':''}>${v}</option>`).join('')}</select></label><p class="small muted">此处没有采集疾病、用药和过敏史，也不会据此生成真实个人处方。</p><button class="primary-button full-button" type="submit">保存档案 ${icon('check')}</button></form></div>`,'编辑我的档案')}
function constitutionList(){openDetail(`<div class="detail-body"><span class="tag">体质科普</span><h2>认识中医九种体质</h2><p class="detail-lead">以下是九种基本类型。下面的提示词仅帮助浏览，不是诊断依据，也不能靠单个感受给自己定型。</p><div class="constitution-grid">${constitutions.map(([n,d],i)=>`<div class="constitution-type"><span>${String(i+1).padStart(2,'0')}</span><h3>${n}</h3><p>${d}</p></div>`).join('')}</div><p class="gentle-note">“湿气重”是日常描述，不等于已经判定为“痰湿质”。正式判定应使用完整标准量表及相应计分方法。</p>${sourceHtml('constitution')}<button class="primary-button full-button" data-action="quiz">开始日常感受试测 ${icon('arrow')}</button></div>`,'中医九种体质')}
function assessmentHistory(){return`<div class="assessment-history">${sectionHead('我的感受记录','MY RECORDS',`<span class="count-label">${state.assessments.length} 份</span>`)}${state.assessments.length?state.assessments.map(r=>`<div class="record-row"><button class="text-button" data-view-assessment="${esc(r.id)}">${esc(new Date(r.createdAt).toLocaleString('zh-CN'))} · 试测参考 →</button><button class="text-button" data-delete-assessment="${esc(r.id)}">删除</button></div>`).join(''):'<p class="empty-copy">完成试测并自愿保存后，可以在这里回看。不会自动判定体质。</p>'}</div>`}
function about(){openDetail(`<div class="detail-body"><div class="about-list"><p>记录只存在这台手机的浏览器里。换一台设备，或清除浏览器数据后，就找不到了。</p><p>你写下的文字和拍的照片，会发送给第三方服务，用来识别吃了什么、大约多少克。</p><p>食物名称会用于在薄荷健康查询营养。查不到的，就标成暂时算不出来，不会编一个数字。</p><p>页面上的「约 X 千卡」是估算。</p><p>这些内容不用于诊断或治疗。身体不舒服时，请寻求专业帮助。</p><p>点开食物上的「数据来源」，可以看到它来自知养食物库还是薄荷健康，以及更细的编号。</p></div><button class="primary-button full-button" data-close="detail">知道了</button></div>`,'隐私与说明')}
async function toggleSave(key){const was=state.saved.includes(key);await writeStore(s=>s.favorite(key));toast(was?'已取消收藏':'已收藏，可在“我的”查看');document.querySelectorAll('[data-save]').forEach(b=>{if(b.dataset.save===key)b.innerHTML=icon('bookmark')+(was?' 收藏':' 已收藏')})}
function cancelRequest(){chatVersion++;requestController?.abort();requestController=null;chatBusy=false;document.querySelectorAll('.message.is-loading').forEach(el=>el.remove());const cancel=document.getElementById('chat-cancel');if(cancel)cancel.hidden=true;const submit=document.getElementById('chat-submit');if(submit)submit.disabled=false}
function newChat(){cancelRequest();history=[];pendingPlans.clear();activePlan=null;contentRef=null;urgentSession=false;document.getElementById('chat-content').innerHTML=''}
function openChat(query=''){if(detail.open)detail.close();if(!document.getElementById('chat-messages')){document.getElementById('chat-content').innerHTML=`<div class="chat-header"><span class="chat-avatar">${icon('spark')}</span><div><h2>知养 AI</h2><p>中式食养 · 起居 · 身心调养</p></div><button class="icon-button" data-action="new-chat" aria-label="重新开始对话">${icon('book')}</button><button class="icon-button" data-close="chat" aria-label="关闭咨询">${icon('close')}</button></div><div class="chat-demo-note">模拟体验 · 真实模型尚未接入</div><div class="chat-context">${activePlan?`正在调整：${esc(activePlan.title)} · 修订 ${activePlan.revision}`:contentRef?'已附带当前内容，方便继续讨论':'饮食偏好按需使用，测评原始答案不会自动发送。'}</div><div id="chat-messages" class="chat-messages" role="log" aria-label="咨询对话" aria-live="polite"><div class="welcome"><span>${icon('spark')}</span><h3>${activePlan?'继续完善这份方案':'今天，想从哪里开始？'}</h3><p>${activePlan?(activePlan.kind==='routine'?'记录你自己选择的准备时间；保存会更新原安排。':'当前可演示把鱼类搭配换为豆腐；保存会更新原方案。'):'欢迎讨论各类健康养生问题。<br>当前先体验预设场景，自由问答等待模型接入。'}</p><div class="welcome-grid">${(activePlan?(activePlan.kind==='routine'?[['把准备时间改为22:30','把准备时间改为22:30']]:[['不吃鱼，换成豆腐','不吃鱼，换成豆腐']]):[['我最近胖了，应该怎么吃？','我想健康减重'],['想增重，三餐怎么安排？','我想健康增重'],['了解日常茶饮','推荐一杯养生茶'],['作息有点乱，怎么调整？','我最近作息有点乱']]).map(([t,q])=>`<button data-chat-send="${q}">${t} ${icon('arrow')}</button>`).join('')}</div></div></div><label class="chat-consent"><input id="use-profile" type="checkbox"> 使用我的饮食目标、习惯和偏好</label><form id="chat-form" class="chat-compose"><label class="sr-only" for="chat-input">输入你想咨询的问题</label><textarea id="chat-input" maxlength="1500" rows="1" placeholder="聊聊饮食、起居，或你想了解的问题"></textarea><button type="submit" aria-label="发送咨询" id="chat-submit">${icon('arrow')}</button></form><div class="chat-footer-note">发送会将问题与当前对话交给本网站服务端。<button class="text-button" data-action="cancel-request" id="chat-cancel" hidden>取消本次回复</button></div>`}chat.setAttribute('aria-label','知养 AI 模拟咨询');if(!chat.open)chat.showModal();if(query)send(query);else if(matchMedia('(min-width:761px)').matches)document.getElementById('chat-input').focus()}
function appendMessage(type,html){const el=document.createElement('div');el.className=`message ${type}`;el.innerHTML=type==='assistant'?`<span class="message-avatar">${icon('spark')}</span><div class="message-body">${html}</div>`:`<div class="user-bubble">${html}</div>`;document.getElementById('chat-messages').append(el);el.scrollIntoView({block:'end',behavior:'instant'});return el}
async function send(text){text=String(text).trim().slice(0,1500);if(!text)return;if(chatBusy)cancelRequest();document.querySelector('.welcome')?.remove();document.getElementById('chat-input').value='';appendMessage('user',esc(text));chatBusy=true;document.getElementById('chat-cancel').hidden=false;const loading=appendMessage('assistant','<span class="typing"><i></i><i></i><i></i></span>');loading.classList.add('is-loading');const current=chatVersion,requestId=createId();requestController=new AbortController();const ownController=requestController;const timeout=setTimeout(()=>ownController.abort(),15000);
 const profileContext=document.getElementById('use-profile').checked?{goal:state.profile.goal,habit:state.profile.habit,preference:state.profile.preference}:{};
 const request={requestId,message:text,history:history.slice(-16),safetyContext:{urgent:urgentSession||history.filter(h=>h.role==='user').some(h=>isExplicitUrgent(h.content)),sensitive:history.filter(h=>h.role==='user').some(h=>isSensitive(h.content))},profileContext,...(activePlan?{activePlan:structuredClone(activePlan)}:{}),...(contentRef?{contentRef}:{} )};history.push({role:'user',content:text});
 try{const reply=await getAgentReply(request,{signal:requestController.signal});if(current!==chatVersion)return;loading.remove();let content=`<p>${esc(reply.text).replace(/\n/g,'<br>')}</p>`;
 if(reply.mode==='urgent_help'){urgentSession=true;pendingPlans.clear();document.querySelectorAll('.chat-plan,.chat-recipes,.chat-choices,.message [data-save-plan]').forEach(el=>el.remove());content=`<div class="urgent-help" role="alert"><strong>请立即寻求专业帮助</strong>${content}</div>`}
 if(reply.planDraft&&!urgentSession){const plan=reply.planDraft;pendingPlans.set(plan.id,plan);content+=`<div class="chat-plan"><span class="tag">搭配示例 · 内容待审核</span><h3>${esc(plan.title)}</h3><dl>${plan.meals.map(m=>`<div><dt>${esc(m.label)}</dt><dd>${esc(m.value)}</dd></div>`).join('')}</dl><p class="small muted">${esc(plan.note)}</p><button class="primary-button" data-save-plan="${esc(plan.id)}">${icon('bookmark')} ${plan.baseRevision?'保存对原方案的调整':'保存到我的方案'}</button></div>`}
 if(reply.contentRefs.length&&!urgentSession)content+=`<div class="chat-recipes">${reply.contentRefs.filter(ref=>ref.type==='recipe').map(({id})=>{const r=recipes.find(x=>x.id===id);return`<button data-chat-recipe="${r.id}">${r.image?`<img src="${r.image}" alt="${r.title}示意">`:`<span class="chat-recipe-icon">${icon('bowl')}</span>`}<span><strong>${r.title}</strong><small>内容示例 · 查看适用说明</small></span>${icon('arrow')}</button>`}).join('')}</div>`;
 if(reply.followUpQuestions.length&&!urgentSession)content+=`<div class="chat-choices">${reply.followUpQuestions.map(q=>`<button data-chat-send="${esc(q)}">${esc(q)}</button>`).join('')}</div>`;
 appendMessage('assistant',content);history.push({role:'assistant',content:reply.text});
 }catch(error){if(current===chatVersion){loading.remove();appendMessage('assistant',`<p>${esc(error.name==='AbortError'?'回复超时，尚未保存任何方案。':error.message||'这次回复未完成。')}</p><button class="outline-button" data-chat-send="${esc(text)}">重试这次咨询</button>`);document.getElementById('chat-input').value=text}}
 finally{clearTimeout(timeout);if(current===chatVersion){chatBusy=false;requestController=null;document.getElementById('chat-cancel').hidden=true;document.getElementById('chat-messages').scrollTop=document.getElementById('chat-messages').scrollHeight}}}
async function savePlan(id){if(urgentSession)return;const p=pendingPlans.get(id);if(!p)return;const saved=await writeStore(s=>s.plan(p));pendingPlans.delete(id);if(activePlan?.id===id)activePlan=saved;document.querySelectorAll('[data-save-plan]').forEach(b=>{if(b.dataset.savePlan===id){b.innerHTML=icon('check')+' 已保存';b.disabled=true}});toast('已保存，可在“我的方案”中继续调整')}

document.addEventListener('click',async e=>{const b=e.target.closest('button,a.brand');if(!b)return;const d=b.dataset;
 if(await assessment.action(b))return;
 try{
 if(await dietPages.onClick(b))return;
 if(b.classList.contains('brand')){e.preventDefault();navigate('home')}
 else if(d.page)navigate(d.page);
 else if(b.hasAttribute('data-chat')){if(activePlan||contentRef)newChat();openChat(d.chat)}
 else if(d.foodTab){foodTab=d.foodTab;navigate('food')}
 else if(d.careTab){careTab=d.careTab;render()}
 else if(d.homeMode){homeMode=d.homeMode;render()}
 else if(d.day){day=d.day;render()}
 else if(d.recipe)recipeDetail(d.recipe);
 else if(d.topic)topicDetail(d.topic);
 else if(d.article)articleDetail(d.article);
 else if(d.lifestyle)lifestyleDetail();
 else if(d.close)(d.close==='chat'?chat:detail).close();
 else if(d.detailChat){newChat();contentRef=d.refId?{type:d.refType,id:d.refId}:null;openChat(d.detailChat)}
 else if(d.chatSend)await send(d.chatSend);
 else if(d.chatRecipe){chat.close();recipeDetail(d.chatRecipe)}
 else if(d.save)await toggleSave(d.save);
 else if(d.savePlan){b.disabled=true;try{await savePlan(d.savePlan)}catch(error){b.disabled=false;throw error}}
 else if(d.adjustPlan){await refreshState();const plan=state.plans.find(p=>p.id===d.adjustPlan);if(!plan)throw new Error('这份方案已被删除');newChat();activePlan=structuredClone(plan);openChat()}
 else if(d.removePlan){await writeStore(s=>s.removePlan(d.removePlan));toast('已移除这份方案')}
 else if(d.viewAssessment){const record=state.assessments.find(r=>r.id===d.viewAssessment);if(record)assessment.view(record)}
 else if(d.deleteAssessment){await writeStore(s=>s.removeAssessment(d.deleteAssessment));toast('已删除这份感受记录')}
 else if(d.action){switch(d.action){
 case'about':case'privacy':about();break;case'ack-privacy':try{localStorage.setItem('zhiyang-privacy-ack','1')}catch{}document.getElementById('first-run').hidden=true;break;
 case'edit-profile':editProfile();break;
 case'constitutions':constitutionList();break;
 case'quiz':await assessment.open();break;
 case'new-chat':newChat();openChat();break;
 case'cancel-request':cancelRequest();appendMessage('assistant','<p>已取消本次回复，尚未保存方案。</p>');break;
 case'retry-storage':await bootStorage();break;
 case'reset':openDetail('<div class="detail-body"><h2>清除本机记录？</h2><p class="detail-lead">将清除这台手机上的饮食记录和每日目标。清除后找不回来。</p><div class="button-row"><button class="outline-button" data-close="detail">先保留</button><button class="primary-button" data-action="confirm-reset">确认清除</button></div></div>','清除本机记录');break;
 case'confirm-reset':{if(!storage)throw new Error('本机存储不可用，无法确认已清除');b.disabled=true;clearing=true;dataEpoch++;newChat();await assessment.reset();try{await writeQueue.catch(()=>{});await storage.clear();state=emptyState();detail.close();navigate('profile');toast('这台手机上的记录已清除')}finally{clearing=false;b.disabled=false}break;}
 }}
 }catch(error){toast(friendlyMessage(error.message,'这次没有完成，请再试一次'))}
});
document.addEventListener('submit',async e=>{try{if(await dietPages.onSubmit(e))return}catch(error){toast(error.message||'没有保存');return}if(e.target.id==='profile-form'){e.preventDefault();const form=e.target,button=form.querySelector('[type=submit]'),f=new FormData(form);button.disabled=true;try{await writeStore(s=>s.profile({name:String(f.get('name')).trim()||'体验用户',goal:String(f.get('goal')),habit:String(f.get('habit')),preference:String(f.get('preference')),updated:new Date().toISOString()}));detail.close();toast('档案已保存，可在咨询时选择使用饮食偏好')}catch(error){toast(error.message||'保存失败，输入仍保留')}finally{button.disabled=false}}else if(e.target.id==='chat-form'){e.preventDefault();send(document.getElementById('chat-input').value)}});
chat.addEventListener('close',cancelRequest);

document.addEventListener('keydown',e=>{if(e.target.id==='chat-input'&&e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send(e.target.value)}});
for(const dialog of[detail,chat])dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()});
let width=innerWidth;window.addEventListener('resize',()=>{if((width<=760)!==(innerWidth<=760)){document.querySelector('.topbar-label').textContent='知养'}width=innerWidth});
page=['home','today','library','profile'].includes(location.hash.slice(1))?location.hash.slice(1):'home';render();try{if(!localStorage.getItem('zhiyang-privacy-ack'))document.getElementById('first-run').hidden=false}catch{}historyAPI(true);await bootStorage();
// Optional WebMCP exposes the same navigation and read-only demo overview as the visible UI.
const context=document.modelContext;
if(context?.registerTool){const life=new AbortController();const tools=[{name:'get_wellness_demo_overview',title:'读取当前页面概览',description:'Read the current page and counts of saved plans and content. Does not expose chat or personal profile data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');return{page,mode:'mock',savedPlans:state.plans.length,savedItems:state.saved.length}}},{name:'navigate_wellness_demo',title:'切换页面',description:'Navigate to an existing page. Does not send a message, assess health, or save a plan.',inputSchema:{type:'object',properties:{page:{type:'string',enum:['home','today','library','food','care','profile']}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).length!==1||!['home','today','library','food','care','profile'].includes(input.page))throw new Error('Invalid page');navigate(input.page);return{page}}}];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>life.abort(),{once:true})}
