export const sources={constitution:{title:'中医体质分类与判定（GB/T 46939—2025）发布说明',url:'https://www.samr.gov.cn/xw/sj/art/2026/art_bbc0d96fbbb741a2a66d2f4f7a44fd82.html'},nutrition:{title:'国家卫健委：中国公民健康素养（2024 年版）',url:'https://www.nhc.gov.cn/xcs/c100123/202405/73a4927142f34152abed875634a3c13b.shtml'},food:{title:'国家卫健委：成人肥胖食养指南问答',url:'https://www.nhc.gov.cn/cms-search/downFiles/6d7f12d8c8da45f0859c1c6be6f99726.pdf'},throat:{title:'NHS：Sore throat',url:'https://www.nhs.uk/symptoms/sore-throat/'},bowel:{title:'NHS：Constipation',url:'https://www.nhs.uk/conditions/constipation/'}};
export const constitutions=[['平和质','平衡与协调'],['气虚质','留意精力与活动感受'],['阳虚质','留意对寒冷的感受'],['阴虚质','留意干燥与燥热感受'],['痰湿质','留意身体困重的感受'],['湿热质','留意湿与热的感受'],['血瘀质','了解相关身体表现'],['气郁质','留意情绪与身体感受'],['特禀质','留意特殊敏感情况']];
export const recipes=[
{id:'breakfast',title:'山药小米粥搭配',category:'三餐搭配',time:'早餐',duration:'约 25 分钟',tag:'温热早餐',desc:'一碗粥之外，也给早餐加一点丰富。',ingredients:['山药、小米与饮用水','鸡蛋或你适合的豆制品','一份新鲜水果'],steps:['山药和小米洗净，按日常煮粥方式煮熟。','搭配鸡蛋或适合自己的其他蛋白质食物。','再加一份水果，让早餐食物种类更丰富。'],note:'这是搭配示例，份量尚未按个人需要计算；对原料过敏时需要替换。',source:'nutrition'},
{id:'lunch',title:'清蒸鱼与时蔬饭',category:'三餐搭配',time:'午餐',duration:'约 30 分钟',tag:'荤素搭配',image:'assets/lunch.jpg',desc:'主食、鱼肉、蔬菜，都给自己留一份。',ingredients:['米饭或杂粮饭','充分蒸熟的鱼肉','绿叶菜与南瓜'],steps:['准备一份主食，鱼肉充分蒸熟。','搭配时蔬，烹调时减少额外油盐。','根据实际饥饱感与个人需求调整份量。'],note:'照片为搭配示意，不代表精确份量或营养计算。对鱼过敏可查看豆腐替换示例。',source:'nutrition'},
{id:'dinner',title:'菌菇豆腐杂粮饭',category:'三餐搭配',time:'晚餐',duration:'约 20 分钟',tag:'清爽家常',desc:'用家常食材，把晚饭吃得简单些。',ingredients:['豆腐、菌菇与绿叶菜','一份杂粮饭','少量烹调用油及调味'],steps:['豆腐与菌菇煮熟或炖熟。','搭配一份绿叶蔬菜和主食。','按自己的实际需求调整，不因减重而直接省略正餐。'],note:'这是家常菜示例，不适用于需要特殊膳食治疗的情况。',source:'nutrition'},
{id:'tea',title:'陈皮红枣温饮',category:'食养茶饮',time:'茶饮',duration:'风味参考',tag:'传统食养',image:'assets/tea.jpg',desc:'淡淡柑橘香，给日常添一杯温饮。',ingredients:['食品用途的陈皮','去核红枣','饮用水'],steps:['选用符合食品用途的原料，按原料包装的食用说明准备。','清洗后充分冲泡或煮制，放至适口温度再饮用。','原料配比与用量留待专业内容审核；本 Demo 不生成个性化草药配方。'],note:'这是风味与页面示例，不宣称祛湿、消肿或减脂疗效。服药、孕哺期、过敏或有特殊健康状况时，先询问专业人员。',source:'food'},
{id:'oats',title:'燕麦酸奶加餐',category:'三餐搭配',time:'加餐',duration:'约 5 分钟',tag:'加餐参考',desc:'给希望增加饮食摄入的人，多一个搭配选择。',ingredients:['适合自己食用的原味酸奶','即食燕麦','水果或适量坚果（无过敏时）'],steps:['根据原料说明准备燕麦。','与酸奶、水果搭配，作为正餐之外的选择。','如果近期体重无意下降或长期吃不下，先咨询专业人员。'],note:'增重不能只靠某种食物。这是搭配示例，未计算个人能量目标。',source:'nutrition'}];
export const lifestyle={id:'sleep',title:'给今晚留一点安静',category:'起居建议',tag:'规律作息',desc:'把休息安排进生活，也允许计划有弹性。',points:['选一个适合自己的睡前准备时间。','把明天需要处理的事情记下来，减少临睡前反复惦记。','建立容易重复的睡前习惯；持续睡眠困扰应寻求专业帮助。']};
export const topics=[
{id:'damp',title:'总觉得湿气重',subtitle:'从饮食与日常习惯聊起',group:'日常状态',icon:'leaf',accent:'green',tips:['先记录你说的“湿气重”具体指什么感受。','从规律三餐、减少过多油盐糖、适度活动等日常习惯入手。','想了解体质，可以先浏览九种类型，再使用经过验证的正式量表。'],boundary:'“湿气重”是你的描述，不能据此直接判定体质或病因。有明显浮肿、持续不适时请就医。',related:'tea',source:'nutrition'},
{id:'throat',title:'嗓子不舒服',subtitle:'饮水、饮食与休息参考',group:'呼吸与咽喉',icon:'wind',accent:'orange',tips:['选择自己可以舒适吞咽的食物，适当饮水。','休息，避开烟雾等刺激。','记录持续时间与变化；症状持续或加重时咨询医生。'],boundary:'若呼吸困难、无法吞咽，或情况迅速恶化，请立即寻求医疗帮助。',related:null,source:'throat'},
{id:'bowel',title:'排便不太顺畅',subtitle:'留意纤维、水分与规律',group:'脾胃与消化',icon:'sun',accent:'green',tips:['在耐受的前提下，逐步增加蔬菜、水果、全谷物等食物。','保持适合自己的饮水与活动习惯；有医嘱限制时遵循医嘱。','记录排便习惯，给自己规律的如厕时间。'],boundary:'出现便血、持续腹痛、体重无意下降，或反复、持续便秘时，请咨询医生。',related:'dinner',source:'bowel'},
{id:'sleep',title:'作息有点乱',subtitle:'从一个小习惯开始',group:'作息与情绪',icon:'moon',accent:'purple',tips:lifestyle.points,boundary:'持续影响白天生活的睡眠问题，不宜只依靠养生建议处理。',related:null,source:'nutrition'},
{id:'weight',title:'最近体重增加',subtitle:'把三餐重新安排好',group:'日常状态',icon:'scale',accent:'orange',tips:['先了解体重变化的时间、幅度与生活变化。','关注整体饮食搭配，不把某杯茶或单一食物当作减重方案。','避免仅凭体重焦虑就采用极端限制饮食。'],boundary:'本 Demo 不判定是否肥胖，也不计算个性化减重目标。快速、无法解释的变化请咨询专业人员。',related:'lunch',source:'food'},
{id:'stress',title:'最近有点紧绷',subtitle:'给忙碌留一个暂停键',group:'作息与情绪',icon:'heart',accent:'purple',tips:['给自己留一小段不用完成任务的时间。','记录让自己紧绷的事，尝试减少一个可调整的负担。','与信任的人交流；持续困扰时寻求专业支持。'],boundary:'这里提供日常生活参考，不评估或治疗心理疾病。',related:null,source:'nutrition'}];
export const articles=[
{id:'season',title:'白露之后，把三餐吃得舒服一点',label:'时令食养',image:'assets/tea.jpg',read:'3 分钟',intro:'季节可以成为调整生活节奏的提醒。具体吃什么，仍要结合食物多样性、自己的偏好与实际需要。',paragraphs:[['从家常食物开始','给餐桌保留主食、蔬菜和适合自己的蛋白质食物。选择当季食材，可以让日常搭配有更多变化。'],['饮品是生活选择','茶饮可以是风味体验，不需要承担减肥、消肿或治疗疾病的任务。留意原料、适用条件和是否额外加糖。'],['给计划留一点余地','忙碌时用更容易准备的搭配，买不到的食材可以替换。适合长期生活的安排，通常需要一点弹性。']],source:'nutrition'},
{id:'balance',title:'想管理体重，先把一顿饭搭配好',label:'饮食知识',image:'assets/lunch.jpg',read:'4 分钟',intro:'“只吃某种食物”和“一顿饭怎么搭配”是不同的问题。先看整体饮食，再考虑具体替换。',paragraphs:[['看看这一餐都有什么','留意主食、蔬菜与蛋白质食物是否都有，也留意饮料、零食和调味带来的额外摄入。'],['先找到容易改变的一处','可以从减少含糖饮料、调整烹调方式等具体习惯开始。个体的能量目标需要充分信息和可靠计算。'],['食养不替代专业评估','有特殊健康状况、近期体重明显变化，或需要治疗性膳食时，先咨询专业人员。']],source:'food'}];

for (const item of [...recipes, ...topics, ...articles]) { item.reviewStatus = "pending"; item.contentVersion = "0.1-draft"; }
